{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "35adc506-2225-4f5f-abf4-e90004becbcd",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from sklearn import metrics\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.pyplot import figure\n",
    "figure(figsize=(20, 2), dpi=80)\n",
    "\n",
    "xcor=[]\n",
    "ycor=[]\n",
    "def click_event(event, x, y, flags, params):\n",
    "  \n",
    "\n",
    "    if event == cv2.EVENT_LBUTTONDOWN: \n",
    "        \n",
    "        ycor.append(y)\n",
    "        xcor.append(x) \n",
    "       \n",
    "          \n",
    "\n",
    "\n",
    "        \n",
    "        font = cv2.FONT_HERSHEY_SIMPLEX\n",
    "        cv2.putText(img, str(x) + ',' +\n",
    "                    str(y), (x,y), font,\n",
    "                    0, (255, 255, 0), 1)\n",
    "        cv2.imshow('image', edges)\n",
    "\n",
    "\n",
    "    if event==cv2.EVENT_RBUTTONDOWN:\n",
    "\n",
    "        font = cv2.FONT_HERSHEY_SIMPLEX\n",
    "        b = img[y, x, 0]\n",
    "        g = img[y, x, 1]\n",
    "        r = img[y, x, 2]\n",
    "        cv2.putText(img, str(b) + ',' +\n",
    "                    str(g) + ',' + str(r),\n",
    "                    (x,y), font, 1,\n",
    "                    (255, 255, 0), 2)\n",
    "        cv2.imshow('image', edges)\n",
    "\n",
    "\n",
    "if __name__==\"__main__\":\n",
    "\n",
    "    im = cv2.imread('/Users/harnoormann/Desktop/Mann/10cm interval Niagara 15may/1.jpg', 1)\n",
    "    img = cv2.resize(im, (6000, 3000))\n",
    "    \n",
    "    \n",
    "    \n",
    "\n",
    "    sobelx = cv2.Sobel(src=img, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5)\n",
    "    sobely = cv2.Sobel(src=img, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5) \n",
    "    sobelxy = cv2.Sobel(src=img, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5) \n",
    "    edges = cv2.Canny(image=img, threshold1=400, threshold2=20, apertureSize=3)\n",
    "    \n",
    "\n",
    "    cv2.imshow('image', edges)\n",
    "\n",
    "\n",
    "    cv2.setMouseCallback('image', click_event)\n",
    "\n",
    "    cv2.waitKey(0)\n",
    "\n",
    "\n",
    "    cv2.destroyAllWindows()\n",
    "\n",
    "\n",
    "    \n",
    "    \n",
    "print(xcor)\n",
    "print(ycor)\n",
    "\n",
    "\n",
    "plt.plot(xcor[1:], ycor[1:])\n",
    "plt.gca().invert_yaxis()\n",
    " \n",
    "plt.show()\n",
    "plt.show()\n",
    "\n",
    "import numpy as np\n",
    "from sklearn import metrics\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.pyplot import figure\n",
    "figure(figsize=(20, 2), dpi=80)\n",
    "\n",
    "dis=((xcor[1]-xcor[0])**2 + (ycor[1]-ycor[0])**2 )\n",
    "print('Area in m2: {}'.format(np.trapz(ycor[1:],xcor[1:])*(0.001369/dis)))\n",
    "print(len(xcor),len(ycor))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
